-- TYT Hazırlık — KONULAR (ders/ünite başlıkları + soru sayıları). Supabase SQL Editor'da çalıştır.
create table if not exists public.topics (
  subject        text not null,
  unit_id        text not null,
  name           text not null,
  sort_order     int  not null default 0,
  question_count int  not null default 0,
  content        text,
  primary key (subject, unit_id)
);
alter table public.topics enable row level security;
drop policy if exists "topics: giris yapinca oku" on public.topics;
create policy "topics: giris yapinca oku" on public.topics for select using (auth.role() = 'authenticated');

delete from public.topics;
insert into public.topics (subject, unit_id, name, sort_order, question_count) values
('turkce','tr-sozcuk','Sözcükte Anlam',0,25),
('turkce','tr-cumle','Cümlede Anlam',1,25),
('turkce','tr-paragraf','Paragraf',2,25),
('turkce','tr-ses','Ses Bilgisi',3,25),
('turkce','tr-yazim','Yazım Kuralları',4,25),
('turkce','tr-noktalama','Noktalama İşaretleri',5,25),
('turkce','tr-adlar','Sözcük Türleri: Ad, Sıfat, Zamir, Zarf',6,25),
('turkce','tr-edat','Edat, Bağlaç ve Ünlem',7,25),
('turkce','tr-anlatim','Anlatım Biçimleri ve Düşünceyi Geliştirme Yolları',8,25),
('turkce','tr-bozukluk','Anlatım Bozuklukları',9,25),
('turkce','tr-ogeler','Cümlenin Ögeleri',10,25),
('turkce','tr-fiil','Fiiller (Kip, Kişi, Ek Fiil)',11,25),
('turkce','tr-tamlama','Tamlamalar',12,25),
('turkce','tr-yapi','Sözcükte Yapı ve Ekler',13,25),
('turkce','tr-fiilimsi','Fiilimsiler',14,25),
('matematik','mat-temel','Temel Kavramlar ve Sayı Kümeleri',0,25),
('matematik','mat-bolme','Bölme ve Bölünebilme',1,25),
('matematik','mat-uslu','Üslü Sayılar',2,25),
('matematik','mat-koklu','Köklü Sayılar',3,25),
('matematik','mat-oran','Oran ve Orantı',4,25),
('matematik','mat-problem','Problem Çözme — Genel Stratejiler',5,25),
('matematik','mat-ondalik','Ondalık Gösterim',6,25),
('matematik','mat-esitsizlik','Basit Eşitsizlikler',7,25),
('matematik','mat-mutlak','Mutlak Değer',8,25),
('matematik','mat-carpan','Çarpanlara Ayırma',9,25),
('matematik','mat-denklem','Denklem Çözme',10,25),
('matematik','mat-sayi','Sayı Problemleri',11,25),
('matematik','mat-yas','Yaş Problemleri',12,25),
('matematik','mat-yuzde','Yüzde, Kâr-Zarar ve Faiz Problemleri',13,25),
('matematik','mat-hareket','Hareket (Hız) Problemleri',14,25),
('matematik','mat-isci','İşçi ve Havuz Problemleri',15,25),
('matematik','mat-kesirprob','Kesir Problemleri',16,25),
('matematik','mat-karisim','Karışım Problemleri',17,25),
('matematik','mat-kume','Kümeler',18,25),
('matematik','mat-mantik','Mantık',19,25),
('matematik','mat-fonksiyon','Fonksiyonlar',20,25),
('matematik','mat-polinom','Polinomlar',21,25),
('matematik','mat-olasilik','Permütasyon, Kombinasyon ve Olasılık',22,25),
('matematik','mat-istatistik','Veri, Grafik ve Temel İstatistik',23,25),
('matematik','mat-rasyonel','Rasyonel Sayılar',24,25),
('matematik','mat-ebobekok','EBOB – EKOK',25,25),
('sosyal','cog-konum','Türkiye''nin Konumu',0,25),
('sosyal','cog-iklim','İklim ve Bitki Örtüsü',1,25),
('sosyal','fel-giris','Felsefeyi Tanıma',2,1),
('sosyal','din-bilgi','Bilgi ve İnanç',3,2),
('sosyal','cog-harita','',4,25),
('sosyal','cog-dunya','Dünya''nın Şekli ve Hareketleri',5,25),
('sosyal','cog-atmosfer','Atmosfer, Sıcaklık, Basınç ve Rüzgârlar',6,25),
('sosyal','cog-ickuvvet','İç Kuvvetler',7,25),
('sosyal','cog-diskuvvet','Dış Kuvvetler',8,25),
('sosyal','cog-su','Su Kaynakları',9,25),
('sosyal','cog-toprak','Topraklar',10,25),
('sosyal','cog-nufus','Nüfus',11,25),
('sosyal','cog-goc','Göçler',12,25),
('sosyal','cog-yerlesme','Yerleşmeler',13,25),
('sosyal','cog-ekonomi','Ekonomik Faaliyetler',14,25),
('sosyal','din-insan','İnsan ve Din',15,25),
('sosyal','din-inanc','İslam ve İnanç',16,25),
('sosyal','din-ibadet','İslam ve İbadetler',17,25),
('sosyal','din-muhammed','Hz. Muhammed''in Hayatı ve Örnekliği',18,25),
('sosyal','din-kuran','Kur''an''ın Anlaşılması',19,25),
('sosyal','din-mezhep','İslam Düşüncesinde Yorumlar (Mezhepler)',20,25),
('sosyal','din-ahlak','Ahlak ve Değerler',21,25),
('sosyal','din-medeniyet','İslam ve Bilim, Kültür ve Medeniyet',22,25),
('sosyal','fel-ilkcag','İlk Çağ Felsefesi (MÖ 6 – MS 2)',23,25),
('sosyal','fel-ortacag','Orta Çağ Felsefesi (MS 2 – MS 15)',24,25),
('sosyal','fel-1517','15. – 17. Yüzyıl Felsefesi',25,25),
('sosyal','fel-1819','18. – 19. Yüzyıl Felsefesi',26,25),
('sosyal','fel-20yy','20. Yüzyıl Felsefesi',27,25),
('sosyal','fel-dusunme','Felsefe ile Düşünme',28,25),
('sosyal','fel-varlik','Varlık Felsefesi',29,25),
('sosyal','fel-bilim','Bilim Felsefesi',30,25),
('sosyal','fel-ahlak','Ahlak Felsefesi',31,25),
('sosyal','fel-sanat','Sanat Felsefesi',32,25),
('sosyal','fel-din','Din Felsefesi',33,25),
('sosyal','fel-siyaset','Siyaset Felsefesi',34,25),
('sosyal','fel-bilgi','Bilgi Felsefesi',35,25),
('sosyal','din-islam','Din ve İslam',36,4),
('sosyal','tar-bilim','Tarih Bilimi ve Zaman',37,26),
('sosyal','tar-ilkcag','İlk Çağ Uygarlıkları',38,27),
('sosyal','tar-ilkturk','İslamiyet Öncesi Türk Tarihi',39,27),
('sosyal','tar-islam','İslam Tarihi ve Medeniyeti',40,27),
('sosyal','tar-turkislam','İlk Türk-İslam Devletleri',41,26),
('sosyal','tar-selcuklu','Türkiye Tarihi ve Selçuklular',42,27),
('sosyal','tar-kurulus','Osmanlı Kuruluş ve Devletleşme',43,26),
('sosyal','tar-klasik','Osmanlı Klasik Dönem',44,26),
('sosyal','tar-degisim','Değişim Çağında Osmanlı',45,26),
('sosyal','tar-modern','19. Yüzyıl Osmanlı Modernleşmesi',46,26),
('sosyal','tar-20yy','20. Yüzyıl Başlarında Osmanlı',47,27),
('sosyal','tar-milli','Millî Mücadele',48,26),
('sosyal','tar-inkilap','Atatürk İlke ve İnkılapları',49,26),
('sosyal','tar-politika','Atatürk Dönemi İç ve Dış Politika',50,26),
('sosyal','tar-cagdas','Çağdaş Türk ve Dünya Tarihi',51,26),
('fen','fiz-hareket','Hareket',0,25),
('fen','fiz-kuvvet','Kuvvet ve Hareket',1,25),
('fen','kim-atom','Atomun Yapisi',2,25),
('fen','kim-periyodik','Periyodik Ozelliklerin Degisme Egilimleri',3,25),
('fen','biy-hucre','Hucre',4,25),
('fen','biy-madde','Hücre Zarından Madde Geçişleri',5,25),
('fen','biy-siniflandirma','Canlıların Sınıflandırılması',6,25),
('fen','biy-alemler','Canlılar Dünyası: Âlemler',7,25),
('fen','biy-virus','Virüsler',8,25),
('fen','biy-mitoz','Mitoz ve Hücre Döngüsü',9,25),
('fen','biy-eseysiz','Eşeysiz Üreme',10,25),
('fen','biy-mayoz','Mayoz ve Eşeyli Üreme',11,25),
('fen','biy-ekosistem','Ekosistem Ekolojisi ve Çevre',12,0),
('fen','biy-ortak','Canlıların Ortak Özellikleri',13,25),
('fen','biy-organizasyon','Canlılarda Organizasyon',14,25),
('fen','biy-bilesen','Canlilarin Temel Bilesenleri',15,25),
('fen','biy-inorganik','İnorganik Bileşikler: Su, Mineraller, Asit-Baz-Tuz',16,25),
('fen','biy-karbonhidrat','Karbonhidratlar',17,25),
('fen','biy-lipit','Lipitler (Yağlar)',18,25),
('fen','biy-protein','Proteinler',19,25),
('fen','biy-enzim','Enzimler',20,25),
('fen','biy-vitamin','Vitaminler ve Hormonlar',21,25),
('fen','biy-nukleik','Nükleik Asitler ve ATP',22,25),
('fen','fiz-giris','Fizik Bilimine Giriş',23,25),
('fen','fiz-madde','Madde ve Özkütle',24,25),
('fen','fiz-enerji','İş, Güç ve Enerji',25,25),
('fen','fiz-isi','Isı ve Sıcaklık',26,25),
('fen','fiz-elektrostatik','Elektrostatik',27,25),
('fen','fiz-elektrik','Elektrik ve Manyetizma',28,25),
('fen','fiz-basinc','Basınç ve Kaldırma Kuvveti',29,25),
('fen','fiz-dalga','Dalgalar',30,25),
('fen','fiz-optik','Optik',31,25),
('fen','kim-simya','Simyadan Kimyaya',32,25),
('fen','kim-disiplin','Kimya Disiplinleri ve Calisma Alanlari',33,25),
('fen','kim-sembol','Kimyanin Sembolik Dili',34,25),
('fen','kim-guvenlik','Kimyada Is Sagligi ve Guvenligi',35,25),
('fen','kim-model','Atom Modelleri',36,25),
('fen','kim-yerlesim','Periyodik Sistemde Yerlesim Esaslari',37,25),
('fen','kim-siniflama','Elementlerin Siniflandirilmasi',38,25),
('fen','kim-turler','Kimyasal Turler ve Etkilesimlerin Siniflandirilmasi',39,25),
('fen','kim-guclu','Guclu Etkilesimler',40,25),
('fen','kim-zayif','Zayif Etkilesimler',41,25),
('fen','kim-degisim','Fiziksel ve Kimyasal Degisimler',42,25),
('fen','kim-hal','Maddenin Fiziksel Halleri',43,25),
('fen','kim-katisivi','Katilar ve Sivilar',44,25),
('fen','kim-gaz','Gazlar ve Plazma',45,25),
('fen','kim-su','Su ve Hayat',46,25),
('fen','kim-cevre','Cevre Kimyasi',47,25),
('fen','kim-kanun','Kimyanin Temel Kanunlari',48,25),
('fen','kim-mol','Mol Kavrami',49,25),
('fen','kim-tepkime','Kimyasal Tepkimeler ve Denklemler',50,25),
('fen','kim-hesap','Kimyasal Tepkimelerde Hesaplamalar',51,25),
('fen','kim-karisim1','Homojen ve Heterojen Karisimlar - I',52,25),
('fen','kim-karisim2','Homojen ve Heterojen Karisimlar - II',53,25),
('fen','kim-ayirma','Ayirma ve Saflastirma Teknikleri',54,25),
('fen','kim-asitbaz','Asitlerin ve Bazlarin Ozellikleri',55,25),
('fen','kim-asittepkime','Asitlerin ve Bazlarin Tepkimeleri',56,25),
('fen','kim-tuz','Asitler, Bazlar ve Tuzlar',57,25),
('fen','kim-gunluk','Yaygin Gunluk Hayat Kimyasallari',58,25),
('fen','kim-kozmetik','Kozmetikler, Ilaclar ve Gidalar',59,25),
('geometri','geo-acilar','Doğruda ve Üçgende Açılar',0,25),
('geometri','geo-alan','Üçgende Alan',1,25);
